# Generated by Django 3.2.7 on 2021-09-29 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deleviredAt',
            new_name='deliveredAt',
        ),
    ]
